# This is a consolidated GitHub Actions workflow that includes the check-links, scan, and spell workflows.
# The workflows run daily at 6AM UTC, and can be triggered manually from the Actions tab.

name: consolidated-workflow

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - &setup-hugo
        name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.98.0'
          extended: true
      - name: Build
        run: hugo --minify
      - name: check html links
        continue-on-error: true
        run: bin/htmltest -c .htmltest.yml -s 2>&1 | tee htmltest.log
      - name: htmltest results
        uses: actions/upload-artifact@v3
        with:
          name: htmltest-report
          path: tmp/.htmltest/htmltest.log
          retention-days: 7

  scan:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-hugo
      - name: Build
        run: hugo --minify
      - name: scan
        run: |
          tools/install-scan.sh
          clamscan -r -i public -l scanlog
      - name: scan results
        uses: actions/upload-artifact@v3
        with:
          name: clamscan-log
          path: scanlog
          retention-days: 7

  spell:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - name: spell
        uses: rojopolis/spellcheck-github-actions@0.30.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
          output_file: spellcheck-output.txt
      - name: spelling results
        uses: actions/upload-artifact@v3
        with:
          name: spellcheck-output
          path: spellcheck-output.txt
          retention-days: 7