
name: spell

# Controls when the workflow will run
on:

  # run once a day at 6AM UTC
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_spelling:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout 
        uses: actions/checkout@v3

      - name: spell
        uses: rojopolis/spellcheck-github-actions@0.30.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown
          output_file: spellcheck-output.txt

      - name: spelling results
        uses: actions/upload-artifact@v3
        with:
          name: spellcheck-output
          path: spellcheck-output.txt
          retention-days: 7 # Default is 90 days

