# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update_stats:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out current repo
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # Runs a single command using the runners shell
      - name: Show Token
        run: |
             echo "${{ secrets.GITHUB_TOKEN }}"
             
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
             
             
      # Test GitHub API issues
      - name: Test GitHUB API
        run: curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/issues
  
      # Run python script to update files
      - name: Run Python script to update files
        run: |
             cd tools/
             pip install -r requirements.txt
             python3 stats_data_generate.py
